name: CI

on:
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * 0,3'
  workflow_dispatch:

jobs:
  build_wheel:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.11']

    steps:
    - name: Checkout github repo
      uses: actions/checkout@v4
      with:
          lfs: True
    - name: Ensure LFS files are pulled
      run: git lfs pull
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'
    - name: Create Wheel
      run: |
          pip install wheel
          python setup.py sdist bdist_wheel
    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/

  test_install:
    runs-on: ${{ matrix.os }}
    needs: [build_wheel]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8, 3.9, "3.10", "3.11"]

    steps:
    - name: Checkout github repo
      uses: actions/checkout@v4
      with:
          lfs: True
    - name: Ensure LFS files are pulled
      run: git lfs pull
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'
    - name: Run tests
      run: |
          echo $pwd
          pip install -v -e .
          cd $RUNNER_TEMP
          echo $pwd
          OutputTest=$(rpt_tests)
          echo "$OutputTest"
          OutputTest=$(echo "$OutputTest" | tail -1)
          if [[ "$OutputTest" != "True" ]]; then
              exit -1
          else
              exit 0
          fi
